abcnews/odyssey

- src/app/components/VideoPlayer/index.js
…where `videoElOrId` is a native `<video>`, but part of the new JWPlayer (not a Phase 1 Mobile native video).
> New video metadata parsing case

- src/app/components/MasterGallery/index.js
- src/app/components/MasterGallery/index.scss
- src/app/components/Nav/index.scss
- src/app/components/VideoEmbed/index.scss
- src/app/components/VideoPlayer/index.js
- src/app/components/VideoPlayer/index.scss
- src/app/components/utilities/full.scss
- src/app/scheduler/index.js
This change instructs `VideoPlayer` components to swap out custom controls for native ones and disable inline playback on short screens (usually phones in landscape orientation). This is implemented as an extra hook into the scheduler that toggles the UI changes for each non-ambient video player dependent on `matchMedia` comparison.
Also in this changeset:
* CSS custom property fallback values
* A fix for exiting fullscreen mode which sometimes throws an error if there was no active element in the underlying document to re-focus.
* The `Nav` bar is no longer shown when the `MasterGallery` is active, and application of its z-index is now conditional so it doesn't appear on top of other elements in fullscreen mode.
* `invalidateClient` in the scheduler now correctly passes arguments to …
> VideoPlayer controls & inline playback is now dependent on screen dimensions.

- package-lock.json
- src/app/components/Header/index.js
If an `<div class="init-interactive" ... >` is the first 'media' inside a `#header` then it will use that as the background media.
Note: If the header is set to `layered` the `u-parallax` class won't be attached like normal. It is assumed the interactive handles it's own sizing/positioning.
> Added support for using `init-interactive` elements as Header media

- src/app/components/Header/index.js
- src/app/meta/index.js
This issue was raised to address our "Interactive Digital Storytelling team" link in Odyssey headers on the desktop site* going to the current page (because the pre-transform DOM element was an anchor element with an empty href property.
Now link-less infoSources will appear as plaintext.
*This also fixed a bug where the mobile site wasn't rendering link-less infoSources at all.
Closes #14
> Meta infoSource optional link

- src/app/components/Caption/index.js
- src/app/components/VideoEmbed/index.js
- src/app/components/VideoPlayer/index.js
- src/app/components/VideoPlayer/stats.js
This adds a `title` property to `VideoPlayer` components which can be used to better label their play buttons for assistive technologies, and enable unique title reporting to Webtrends.
If you don't pass the property, a unique title is created (a simple incrementing uppercase ASCII letter until we come up with something better).
The change includes the Webtrends tracking correction, as well as a slight modification of the `VideoEmbed` component so that it can pass the `title` property to its child `VideoPlayer`.
> Add VideoPlayer title property

- src/app/components/Header/index.js
Previously, having an interactive in the header would erroneously ignore any paragraph nodes for use as `misc-els`.
> Interactive header with misc els

- src/app/components/Block/index.js
- src/app/components/Header/index.js
- src/app/components/VideoEmbed/index.js
- src/app/components/VideoPlayer/index.js
The standard "high resolution" video source we get from CoreMedia is currently 1024x576px.
Originally we were loading that source on desktop, and the next-best source on mobile (which was only 512px wide, and looked terrible on full-screen cover videos, so we changed the logic to always use the 1024px wide source on mobile, except for inline players.
This resulted in a lot of wasted video pixels due to Odyssey's virtual cropping of 16:9 video to 3:4/1:1, so we began experimenting with alternative aspect ratio _sources_ (and higher resolution video across the board).
This change allows us to filter the available sources, so that mobile devices only use the next-best video if we can be sure it is also high resolution (which we'll be putting into CoreMedia as a square crop, by convention).
> VideoPlayer high resolution source selection logic change

- src/app/components/Gallery/index.js
- src/app/index.js
- src/app/utils/anchors.js
This series of commits removes deprecated anchors used during the development of Odyssey (back when we called it Narricle).
Specifically:
* `#cover`/`#endcover` is no longer an alias for `#block`/`#endblock`
* `#gallerytiled`/`#endgallery` is no longer an alias for `#mosaic`/`#endmosaic`
* `#image` & `#video` are no longer aliases for `#config` when preceding their respective embeds
**NOTE**: After this change is released, these old anchors will stop working.
I've already done the work in Core to remove usage of these old anchors in every Odyssey story (even drafts). Please check any snippets you're storing in Editorial Notes (or outside Core) to avoid accidentally dropping old anchors into new stories.
To help you catch accidental usage, Odyssey now logs them to the browser console, …
> So long, old #anchors

- src/app/components/Block/index.js
- src/app/components/Header/index.js
- src/app/components/VideoEmbed/index.js
- src/app/components/VideoPlayer/index.js
- src/app/components/VideoPlayer/utils.js
- src/app/index.js
- src/constants.js
This set of changes enables a couple of features…
**First**, it enables a new `#video` marker, which works the same way as the `#youtube` marker, e.g.:
```
#video9400772
```
Put ^^^that^^^ anywhere in your story, and it will be transformed into a VideoEmbed (missing a Caption). This also supports preceding `#config` options, just like standard video embeds.
If you put it as the first child of a Header or Block, it will load an ambient VideoPlayer to use as the background media.
**Second**, it adds a new config option to Header and Block, called `supplant`. It allows you to use different media for different platforms, e.g. an image in environments that don't support Odyssey and a video (defined by a `#video` marker) for those that do.
This stops any environment showing both the image and …
> New #video embed marker; alternative Header/Block media

- src/app/components/Block/index.js
- src/app/components/Picture/index.js
- src/app/components/Picture/index.scss
- src/app/components/VideoPlayer/index.js
- src/app/components/VideoPlayer/index.scss
- src/app/components/YouTubePlayer/index.js
- src/app/components/YouTubePlayer/index.scss
- src/app/components/utilities/sizer.scss
...which is currently able to be passed through Block config strings.
This keeps the media within its parent's constraints. Outside the letter/pillar-box, a dimmed blurred image appears (either the original image placeholder, or the video thumbnail).
> Added 'contain' option to Picture, VideoPlayer and YouTubePlayer

- src/app/components/Block/index.scss
- src/app/components/Header/index.js
- src/app/components/Header/index.scss
This new header variant looks the same as a layered Header, but has no media of its own. Instead, it negates its own physical space with negative margin, so the next component that follows it, sits beneath.
The rationale for this is our need to have a Header content that blends seamlessly with a Block / Scrollyteller, and leveraging the Block's media seemed the cleanest way to pull it off.
I also tidied up the hierarchy of variant effects in Headers, so that all floating headers enforce the layered appearance, and as a result, all layered variants enforce the dark appearance (white text on black). Floating headers are also strict about not using media, so they behave as if you applied the nomedia variant to the Header.
Blocks have also been modified so that they create additional empty …
> Added new 'floating' variant to Header for seamless integration with following Block content/media.

- src/app/components/Header/index.scss
- src/app/reset/index.scss
On light-mode (normal mode) when you specify a background colour using --bg:#473947 the colour spills up behind the header and also below the article.
This fixes it so behaviour is consistent with when you set a background colour in dark mode ie. the header will be dark and the content background will be --bg:#473947 and below the article will be light as normal.
This doesn't completely address all of #34 but @colingourlay and I reckon we can close it now.
> Bg color light mode fix

- src/app/components/Block/index.js
- src/app/components/Block/index.scss
Using `#markleft`, `#markright`, or `#markcenter` within a piecemeal block will override the alignment setting of the block, for each panel until the next background image (or the next `#mark` override).
> Added support for overriding left and right in piecemeal blocks

- src/app/components/Block/index.scss
- src/app/components/Recirculation/index.js
- src/app/components/Recirculation/index.scss
- src/app/index.js
- src/app/meta/index.js
- src/app/reset/index.js
- src/app/reset/index.scss
- src/app/utils/capi.js
A recirculation card is similar to a Teaser (Viewtype: WYSIWYG) that we’d currently manually create and embed in our standard article template. They have a title, plus an image and teaser text if they’re available.
The below example was created by adding at least one story to Related, then inserting a #related tag where you want it to appear.
* The title displayed is first available of: **Short Teaser Title** > **Teaser Title** > **Title**.
* The image displayed is the first available of: **Thumbnail Image** > **Media** (Image) > (none).
* The teaser text displayed is the first available of: **Short Teaser Text** > **Teaser Text** > (none).
Because recirculation cards are all tag-based, they won’t appear in syndicated content. Related stories will appear together (at the bottom) …
> Recirculation Cards

- src/app/components/Block/index.js
- src/app/components/Gallery/index.js
- src/app/components/Header/index.js
- src/app/components/VideoEmbed/index.js
- src/app/components/VideoPlayer/index.js
- src/app/components/VideoPlayer/utils.js
We're doing away with the horrible pattern that currently exists within Odyssey, where VideoPlayers are rendered in a bunch of places, first as placeholder `div`s, then substituted with proper components once their required props (poster image and .mp4 source URLs) are asynchronously fetched & parsed from video detail page HTML (ewwww).
The existing pattern was due to the variety of ways that Core can render videos (with and without the data we need to make our own components) across different phases / platforms.
Now, we're using the Content API everywhere (even if pieces of the metadata can be parsed from the current article's DOM / HTML). Consistency will be more important than # of requests going forward.
The VideoPlayer component now loads its own metadata once rendered as a shell, so …
> Self-loading VideoPlayer component

- package-lock.json
- src/app/components/StoryTeaserEmbed/index.js
Only accept teasers that have a title, a _self-targeting link and an image, but not bundle an interactive (such as `interactive-podcast-wysiwyg`, which currently fails intermittently due to the async loading nature of it and `odyssey`).
>  WYSIWYG teasers will only be transformed into StoryTeaserEmbeds if they don't contain interactives

- package-lock.json
- package.json
- src/app/components/GalleryEmbed/index.js
- src/app/components/Header/index.js
- src/app/components/Recirculation/index.js
- src/app/components/VideoPlayer/utils.js
- src/app/components/WhatNext/index.js
* Replace [`@abcnews/capi-fetch`](https://github.com/abcnews/capi-fetch) with [`@abcnews/terminus-fetch`](https://github.com/abcnews/terminus-fetch), which does the same job but with different live/preview API endpoints, and uses News' API key
* Update document structure in usage across various components (notably our `VideoPlayer`)
Note: This removes the need for a separate ImageProxy document fetch for video player poster images, as everything we need is now on the Video document ✨
> Replace C(G)API with Terminus's content APIs

- src/app/components/Picture/index.js
- src/app/components/Picture/index.scss
This massively reduces the number of stacking contexts that need to be painted / held in memory, and should reduce the number of crashes in Mobile Safari.
> Hide Pictures that aren't loaded or loading.

- public/share.html
- src/app/components/Block/content.scss
- src/app/components/Header/index.js
- src/app/components/Header/index.scss
- src/app/components/Header/variables.scss
- src/app/components/Main/index.js
- src/app/components/Main/index.scss
- src/app/components/Main/variables.scss
- src/app/components/ScrollHint/index.scss
- src/app/reset/index.js
- src/constants.scss
* Improve determination of Header (and Header media) height, by using sensible defaults (which persist on IE11), and CSS Custom Properties to allow them to update, based on the viewport size and height of things that precede the Main component (like nav bars).
* This dynamic variable calculation means that we no longer need specific styles for the ABC app (because the nav isn't rendered and the Main component will correctly have offsetTop=0).
* The Header content 'peek' on non-layered Headers can now self-adjust it's height to the number of lines in the story title.
* ScrollHints now appear in a better location. inside Headers.
* A better fix is now in place for Header parallax components in Firefox.
> An effort to reduce magic number use in SCSS, with added bonuses

- src/app/components/Block/index.scss
- src/app/components/Comments/index.scss
- src/app/components/Gallery/index.scss
- src/app/components/Header/index.js
- src/app/components/Header/index.scss
- src/app/components/Sizer/index.scss
- src/app/components/VideoPlayer/index.scss
- src/app/components/YouTubePlayer/index.scss
- src/app/components/utilities/blend-luminosity.scss
- src/app/components/utilities/richtext.scss
- src/app/reset/index.scss
- src/constants.scss
`Header` and `Block` components now only explicitly set a background colour if they oppose the current mode. For example, if `dark-mode` is not enabled, a `Header`'s background will now effectively be transparent, because it can depend on the underlying document background colour. This way, when we set a theme background colour, those components will now share it.
We used to hack this feature into stories such as @drzax's crypto explainer and the upcoming happiness and unpaid labour stories. DSI and CPH have also had to hack it in too, and it's pretty obvious at this point that this should be Odyssey's default behaviour.
Previously, there was no way to define a light header on a dark mode document. Now, you can put `light` in the opening header tag to define this. Dark mode used to always …
> Header and Block background colours are only set when they oppose the current mode

- src/app/components/Gallery/index.js
- src/app/components/Gallery/index.scss
- src/app/components/Quote/index.js
- src/app/components/Sizer/index.js
- src/app/components/UQuote/index.js
- src/app/index.js
- src/constants.js
- src/polyfills/index.js
Pull-quotes in #gallery/#mosaic sections will now be included as items in their respective Gallery/Mosaic components, horizontally and vertically centred within fixed size tiles.
This opens up the option of having a swipable gallery of quotes, or a mosaic that combines photos/videos/quotes in visually interesting ways.
The only difference between normal quotes and gallery item quotes is the limited canvas size (especially noticable on small devices with 2-3 items in a mosaic row, so we'll have to limit the amount of text in the quotes (and visually confirm it doesn't overflow).
> Quotes in Galleries
